version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    .\build.ps1
test: off
artifacts:  
- path: .\.nupkg\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/jacobwhite-ci/api/v2/package
  api_key:
    secure: BGrbZO/dcbaL1/huAhzfQL2XpEQLhsev5Q2ucBo0ltbSKj3IF7RtbmjcWMETa3Re
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: AniXyttMFlyUupiWJw0z34bzCuOrQfcJ4SY/rbjR/pzUHDaLRmqM5PcBMgNbBGgU
  on:
    branch: master
    appveyor_repo_tag: true